# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'
variables:
  scheme: 'HelloWorld'
  sdk: 'iphoneos'
  configuration: 'Debug'
steps:
#- task: Xcode@5
#displayName: 'Build the tests'
#inputs:
#actions: 'test'
#scheme: 'HelloWorld'
#sdk: 'iphoneos'
#configuration: 'Release'
#xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
#xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
- task: Xcode@5
  displayName: 'Run Tests'
  inputs:
    actions: 'test'
    scheme: '$(scheme)'
    sdk: 'iphonesimulator'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
    destinationSimulators: 'iPhone 7'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'

- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'build'
    scheme: '$(scheme)'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
