# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: Xcode@5
displayName: 'Running XCTest'
	inputs:
		actions: 'test'
		scheme:  'HelloWorld'#'$(scheme)'
		sdk: 'iphoneos'
		configuration: 'Release'
		xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
		packageApp: false
		xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
#signingOption: "auto"

- task: Xcode@5
  displayName: 'Build the app using Xcode'
  inputs:
    actions: 'build'
    scheme: 'HelloWorld'
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
